
<!-- <?xml version='1.0' encoding='UTF-8'?> -->

 <!DOCTYPE regexps [
 <!--
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/regexps.dtd

--><!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE regexps SYSTEM "regexps.dtd">

    <regexps>
    ...
    </regexps>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT item (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT def (#PCDATA|item|insert)*>
<!ATTLIST def
    desc CDATA #IMPLIED
    type CDATA #REQUIRED
    id CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT insert EMPTY>
<!ATTLIST insert
    idref CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT regexp (#PCDATA|insert)*>
<!ATTLIST regexp
    parsegroup CDATA #REQUIRED
  >


<!ELEMENT unique EMPTY>

<!-- Put your DTDDoc comment here. -->
<!ELEMENT node (regexp, unique?, child*)>
<!ATTLIST node
    value CDATA #IMPLIED
    id CDATA #REQUIRED
    type CDATA #REQUIRED
    saf CDATA #IMPLIED
  >

<!-- Put your DTDDoc comment here. -->
<!ELEMENT child EMPTY>
<!ATTLIST child
    id CDATA #REQUIRED
    type CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT top (child)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT regexps (top, tlrs?, node*, def*)>
 
 ]>

<!--
  - XML structure
  -
  - Start with <top>
  - 
  - <child type=Xxx id=Yyy>
  -     refer to <node type=Xxx id=Yyy value=Zzz>
  - 
  - <regexp> in <node> matches a block of data
  -     'parsegroup' specifies regexp match group for further parsing
  -
  - <node type=Xxx id=Yyy value=Zzz>  ==>  <Xxx type=Zzz> in output XML
  -     unless value = blank          ==>  <Xxx>
  -     unless value = ".."           ==>  no markup
  -
  - <insert idref=Xxx> within <regexp>
  -     replaced with contents of <def id=Xxx>
  -->
<regexps>

<top>
    <child type="property" id="elemanal"/>
    <child type="spectrum" id="hnmr"/>
    <child type="spectrum" id="cnmr"/>
    <child type="spectrum" id="unknownNmr"/>
    <child type="spectrum" id="ir"/>
    <child type="spectrum" id="uv"/>
    <child type="property" id="hrms"/>
    <child type="spectrum" id="massSpec"/>
    <child type="property" id="nature"/>
    <child type="property" id="yield"/>
    <child type="property" id="mp"/>
    <child type="property" id="bp"/>
    <child type="property" id="optrot"/>
    <child type="property" id="rf"/>
    <child type="property" id="refractiveindex"/>
    <child type="property" id="quantity"/>
    <child type="property" id="state"/>
</top>
                                                                                <!-- formula -->                                                                                <!-- elem anal -->
<node type="property" id="elemanal" value="elemAnal">
    <regexp parsegroup="0">
        [\[\(]?
        (
            <insert idref="elemAnalBlock"/> [;\.\s]*?
        ){2}
        [\)\]]?
    </regexp>
    <child type="quantity" id="elemanalFormula"/>
    <child type="quantity" id="elemanalRequired"/>
    <child type="quantity" id="elemanalFound"/>
</node>

<node type="quantity" id="elemanalFormula" value="formula">
    <regexp parsegroup="1">
        ((?=\w{4})<insert idref="FORMULA"/>)
    </regexp>
</node>

<node type="quantity" id="elemanalRequired" value="required">
    <regexp parsegroup="1">
        (?:
            <insert idref="elemAnalRequired"/>
        )
        ({1}
            <insert idref="elemAnalData"/>
        )
    </regexp>
</node>

<node type="quantity" id="elemanalFound" value="found">
    <regexp parsegroup="1">
        (?:
            <insert idref="elemAnalFound"/>
        )
        ({1}
            <insert idref="elemAnalData"/>
        )
    </regexp>
</node>


                                                                                <!-- H-NMR -->
<!-- TODO: something better than the current nmrDelta kludge - delta isn't a "word"
character, and so doesn't create word boundaries in the right way -->

<node type="spectrum" id="hnmr" value="hnmr">
    <regexp parsegroup="0">
        <insert idref="nmrDelta" />?
        \b
        <insert idref="hNmr.Prolog"/>
        (?: \W* (?:for|of)\s+\w+ (?: (![\(\);]).)*?)?
        <insert idref="nmrMethod"/>?
        (\W+(<insert idref="nmrDelta"/>|H)+)?
        [\s:=]*?
        <!-- as opposed to [\s:=]+? -->
        (?: \W*ppm\W*?)?
        (?: peaks\s+at\s+)?
        (?:\s*<insert idref="nmrDelta"/>\s+)?
        <insert idref="nmrPeakBlock"/>
        (?:\s*ppm)?
    </regexp>
     <child type="quantity" id="hnmrSolvent"/>
     <child type="quantity" id="hnmrStandard"/>
     <child type="quantity" id="hnmrFrequency"/>
     <child type="quantity" id="hnmrTemperature"/>
     <child type="peaks" id="hnmr"/>
</node>

<node type="quantity" id="hnmrSolvent" value="solvent">
    <regexp parsegroup="1">
        \W(<insert idref="nmrListSolvent"/>)\b
    </regexp>
</node>

<node type="quantity" id="hnmrStandard" value="standard">
    <regexp parsegroup="1">
        \W(<insert idref="nmrListStandard"/>)\b
    </regexp>
</node>

<node type="quantity" id="hnmrFrequency" value="frequency">
    <regexp parsegroup="1">
        \b (
            <insert idref="FLOAT"/> \s* MHz
        ) \b
    </regexp>
    <unique/>
    <child type="value" id="value"/>
    <child type="units" id="frequency"/>
</node>

<node type="quantity" id="hnmrTemperature" value="temperature">
    <regexp parsegroup="1">
        \b(<insert idref="FLOAT"/>)\s*K\b
    </regexp>
    <child type="value" id="value"/>
    <child type="units" id="temp"/>
</node>

<node type="peaks" id="hnmr" value="..">
    <regexp parsegroup="1">
        (<insert idref="nmrPeakBlock"/>)$
    </regexp>
    <child type="peak" id="hnmr"/>
</node>

<node type="peak" id="hnmr">
    <regexp parsegroup="1">
        (<insert idref="nmrPeak"/>)
    </regexp>
    <child type="quantity" id="hnmrPointer"/>
    <child type="quantity" id="hnmrShift"/>
    <child type="quantity" id="hnmrPeakType"/>
    <child type="quantity" id="hnmrIntegral"/>
    <child type="quantity" id="hnmrCoupling"/>
    <child type="quantity" id="hnmrComment"/>
</node>

<node type="quantity" id="hnmrPointer" value="..">
    <regexp parsegroup="1">
        ((NMR\W*?)?\bdH|(1H\W+?NMR(\W*?)))
    </regexp>
</node>

<node type="quantity" id="hnmrShift" value="shift">
    <regexp parsegroup="1">
	<!-- requiring a word boundary at the start prevents the correct
	recognition of negative values as - isn't a word character. -->
        (?:^|\W)(
            <insert idref="VALUE"/>
        ) \b
    </regexp>
    <unique/>
    <child type="value" id="value"/>
</node>

<node type="quantity" id="hnmrPeakType" value="peaktype">
    <regexp parsegroup="1">
        <insert idref="nmrPeakType"/>
    </regexp>
    <unique/>
</node>

<node type="quantity" id="hnmrIntegral" value="integral">
    <regexp parsegroup="1">
        \&lt; (
            <insert idref="VALUE"/>
            \s*
            H
        ) \b
    </regexp>
    <unique/>
    <child type="value" id="value"/>
    <child type="units" id="hnmrIntegral"/>
</node>

<node type="units" id="hnmrIntegral">
    <regexp parsegroup="1">
        ( H )
    </regexp>
</node>

<node type="quantity" id="hnmrCoupling" value="coupling">
    <regexp parsegroup="1">
        \b J \W*?
        (
            <insert idref="FLOAT"/> (\s*Hz)?
            (?: \s* (?: , | and ) \s* <insert idref="FLOAT"/> (\s*Hz)? )* 
        ) \b(?!\s*[<insert idref="HYPHENCHARACTERS"/>x√ó])
        <!-- inserting HYPHEN here breaks e.g. 1H NMR: 2.3 (d, J = 3.1 and 2.2 Hz, 2H), 2.45 (2H, d, J=3.1 and 2.2Hz) -->
    </regexp>
    <unique/>
    <child type="value" id="value"/>
    <child type="units" id="frequency"/>
</node>

<node type="quantity" id="hnmrComment" value="comment">
    <regexp parsegroup="1">
        ^\s*[\(\[\{]? [\s,]* (.+?) [\}\]\)] [^\}\]\)]*$
    </regexp>
</node>



<!-- for NMR spectra that don't explicitly declare their element  -->
<node type="spectrum" id="unknownNmr" value="unknownNmr">
    <regexp parsegroup="0">
        <insert idref="nmrDelta" />?
        \b
        <insert idref="unknownNmr.Prolog"/>
        (?: \W* (?:for|of)\s+\w+ (?: (![\(\);]).)*?)?
        <insert idref="nmrMethod"/>?
        (\W+<insert idref="nmrDelta"/>)?
        [\s:=]*?
        <!-- as opposed to [\s:=]+? -->
        (?: \W*ppm\W*?)?
        (?: peaks\s+at\s+)?
        (?:\s*<insert idref="nmrDelta"/>\s+)?
        <insert idref="nmrPeakBlock"/>
        (?:\s*ppm)?
    </regexp>
		<!-- here -->
     <child type="quantity" id="hnmrSolvent"/>
		<!-- here -->
     <child type="quantity" id="hnmrStandard"/>
		<!-- here -->
     <child type="quantity" id="hnmrFrequency"/>
		<!-- here -->
     <child type="quantity" id="hnmrTemperature"/>
		<!-- here -->
     <child type="peaks" id="hnmr"/>
</node>


                                                                                <!-- C-NMR -->

<node type="spectrum" id="cnmr" value="cnmr">
    <regexp parsegroup="0">
        <insert idref="nmrDelta" />?
        \b
        <insert idref="cNmr.Prolog"/>
        (?: \W* (?:for|of)\s+\w+ (?: (![\(\);]).)*?)?
        <insert idref="nmrMethod"/>?
        (\W+(<insert idref="nmrDelta"/>|C)+)?
        [\s:=]*?
        (?: \W*ppm\W*?)?
        (?: peaks\s+at\s+)?
        (?:\s*<insert idref="nmrDelta"/>\s+)?
        <insert idref="nmrPeakBlock"/>
        (?:\s*ppm)?
    </regexp>
     <child type="quantity" id="nmrSolvent"/>
     <child type="quantity" id="nmrStandard"/>
     <child type="quantity" id="nmrFrequency"/>
     <child type="quantity" id="nmrTemperature"/>
     <child type="peaks" id="cnmr"/>
</node>

<node type="quantity" id="nmrSolvent" value="solvent">
    <regexp parsegroup="1">
        \W (
            <insert idref="nmrListSolvent"/>
        ) \b
    </regexp>
</node>

<node type="quantity" id="nmrStandard" value="standard">
    <regexp parsegroup="1">
        \W ( 
            <insert idref="nmrListStandard"/>
        ) \b
    </regexp>
</node>

<node type="quantity" id="nmrFrequency" value="frequency">
    <regexp parsegroup="1">
        \b (
            <insert idref="FLOAT"/>
            \s* MHz
        ) \b
    </regexp>
    <unique/>
    <child type="value" id="value"/>
    <child type="units" id="frequency"/>
</node>

<node type="quantity" id="nmrTemperature" value="temperature">
    <regexp parsegroup="1">
        \b (
            <insert idref="FLOAT"/>
            \s* K
        ) \b
    </regexp>
    <child type="value" id="value"/>
    <child type="units" id="temp"/>
</node>

<node type="peaks" id="cnmr" value="..">
    <regexp parsegroup="1">
        (
            <insert idref="nmrPeakBlock"/>
        )$
    </regexp>
    <child type="peak" id="cnmr"/>
</node>

<node type="peak" id="cnmr">
    <regexp parsegroup="1">
        (
            <insert idref="nmrPeak"/>
        )
    </regexp>
    <child type="quantity" id="cnmrPointer"/>
    <child type="quantity" id="cnmrShift"/>
    <child type="quantity" id="cnmrPeakType"/>
    <child type="quantity" id="cnmrComment"/>
</node>

<node type="quantity" id="cnmrPointer" value="..">
    <regexp parsegroup="1">
        ((NMR\W*?)?\bdC|(13C\W+?NMR(\W*?)))
    </regexp>
</node>

<node type="quantity" id="cnmrShift" value="shift">
    <regexp parsegroup="1">
	<!-- requiring a word boundary at the start prevents the correct
	recognition of negative values as - isn't a word character -->
		(
            <insert idref="VALUE"/>
        ) \b
    </regexp>
    <unique/>
    <child type="value" id="value"/>
</node>


<node type="quantity" id="cnmrPeakType" value="peaktype">
    <regexp parsegroup="1">
        <insert idref="nmrPeakType"/>
    </regexp>
</node>

<node type="quantity" id="cnmrComment" value="comment">
    <regexp parsegroup="1">
        ^[^\(\[\{]* [\(\[\{] [\s,]* (.*?) [\s,]* [\}\]\)] [^\}\]\)]*$
    </regexp>
</node>


                                                                                <!-- IR -->
<node type="spectrum" id="ir" value="ir">
    <regexp parsegroup="0">
        (
                (?x-i:
                        IR(?=\D) \s* <insert idref="BRACKET"/>? \W*? (?: 
                        [vun??ŒΩ]?max  \s* <insert idref="BRACKET"/>? \W*? )?
                |	[vun??ŒΩ]max \s* <insert idref="BRACKET"/>? \W*?
                )
                (?: <insert idref="irSpecUnit"/> [\s:]* )? (?: 
                <insert idref="BRACKET"/> [\s:]* )? (?: n [\s:]* )? 
                <insert idref="irSpecPeakBlock"/> (?: \s* 
                <insert idref="irSpecUnit"/> )?
        |
                [a-z]?max \s* (?: <insert idref="BRACKET"/> \W*? )?
                (?:
                        (?: <insert idref="irSpecUnit"/> [\s:]* ) (?: 
                        <insert idref="BRACKET"/> [\s:]* )? (?: n [\s:]* )? 
                        <insert idref="irSpecPeakBlock"/>
                |	(?: n [\s:]* )? <insert idref="irSpecPeakBlock"/> 
                        (?: \s* <insert idref="irSpecUnit"/> )
                )
        )
    </regexp>
    <child type="quantity" id="irForm"/>
    <child type="quantity" id="irPlate"/>
    <child type="peaks" id="ir"/>
</node>

<node type="quantity" id="irForm" value="form">
    <regexp parsegroup="1">
        \b (
            <insert idref="irSpecListForm"/>
        ) \b
    </regexp>
</node>

<node type="quantity" id="irPlate" value="plate">
    <regexp parsegroup="1">
        \b (
            <insert idref="irSpecListPlate"/>
        ) \b
    </regexp>
</node>

<node type="peaks" id="ir" value="..">
    <regexp parsegroup="1">
        (?!
            1 \b
        )
        (
            <insert idref="irSpecPeakBlock"/>
        )
    </regexp>
    <child type="peak" id="ir"/>
</node>

<node type="peak" id="ir">
    <regexp parsegroup="1">
        (
            <insert idref="irSpecPeak"/>
        )
    </regexp>
    <child type="quantity" id="irVmax"/>
    <child type="quantity" id="irPeakType"/>
    <child type="quantity" id="irComment"/>
</node>

<node type="quantity" id="irVmax" value="vmax">
    <regexp parsegroup="1">
        \b (
            <insert idref="VALUE"/>
        ) \b
    </regexp>
    <unique/>
    <child type="value" id="value"/>
</node>

<node type="quantity" id="irPeakType" value="peaktype">
    <regexp parsegroup="1">
        \&lt; (
            (?:
                <insert idref="irSpecListPeakType"/>
                [\s,]*?
            )+
        )
        \&gt;\.?
    </regexp>
</node>

<node type="quantity" id="irComment" value="comment">
    <regexp parsegroup="1">
        \(
            [\s,]*
            (.*)
            \s*
        \)
    </regexp>
</node>


                                                                                <!-- UV -->
<node type="spectrum" id="uv" value="uv">
    <regexp parsegroup="0">
        (
            electronic \s spectrum
            .*?
        )?
        (
            (?:
                (?: [?Œªl]max | UV (?: \s* [?Œªl]?max)? )
                \W*?
            )
            (?: <insert idref="BRACKET"/> \W*? )?
            (?: nm [\s*:] )?
            (?: <insert idref="BRACKET"/> [\s*:] )?
            <insert idref="uvSpecPeakBlock"/>
            (?: \s* nm )?
        |

            max \W*? (?: <insert idref="BRACKET"/> \W*? )?
            (?:
                nm [\s:]*
                (?: <insert idref="BRACKET"/> [\s:]* )?
                <insert idref="uvSpecPeakBlock"/>
            |	<insert idref="uvSpecPeakBlock"/> \s* nm
            )
        )
    </regexp>
    <child type="quantity" id="uvSolvent"/>
    <child type="peaks" id="uv"/>
</node>

<node type="quantity" id="uvSolvent" value="solvent">
    <regexp parsegroup="1">
        \b (
            <insert idref="uvSpecListSolvent"/>
        ) \b
    </regexp>
</node>

<node type="peaks" id="uv" value="..">
    <regexp parsegroup="1">
        (
            <insert idref="uvSpecPeakBlock"/>
        )
    </regexp>
    <child type="peak" id="uv"/>
</node>

<node type="peak" id="uv">
    <regexp parsegroup="1">
        (
            <insert idref="uvSpecPeak"/>
        )
    </regexp>
    <child type="quantity" id="uvLmax"/>
    <child type="quantity" id="uvPeakType"/>
    <child type="quantity" id="uvE"/>
    <child type="quantity" id="uvLogE"/>
</node>

<node type="quantity" id="uvLmax" value="lmax">
    <regexp parsegroup="1">
        \b (
            <insert idref="VALUE"/>
        ) \b
    </regexp>
    <unique/>
    <child type="value" id="value"/>
</node>

<node type="quantity" id="uvPeakType" value="peaktype">
    <regexp parsegroup="1">
        \b(<insert idref="uvSpecListPeakType"/>)\b\.?
    </regexp>
</node>

<node type="quantity" id="uvE" value="E">
    <regexp parsegroup="1">
        \(
            [^\)]*?
            (?!
                <insert idref="HYPHEN"/>
            )
            (
                \d{1,2}
                \s?
                \d{3}
            )
    </regexp>
    <unique/>
    <child type="value" id="value"/>
</node>

<node type="quantity" id="uvLogE" value="logE">
    <regexp parsegroup="1">
        \(
            [^\)]*?
            (
                \d+
                \.
                \d+
            )
    </regexp>
    <unique/>
    <child type="value" id="value"/>
</node>




                                                                                <!-- HRMS -->
<node type="property" id="hrms" value="hrms">
    <regexp parsegroup="0">
        [\(\[]?
        <insert idref="hrmsProlog"/>?
        (
            <insert idref="hrmsBlock"/>
            \W*
            <insert idref="hrmsPadding"/>*
            \W*
            <insert idref="hrmsBlock"/>
        )
        [\)\]]?
    </regexp>
    <child type="quantity" id="hrmsFormula"/>
    <child type="quantity" id="hrmsIon"/>
    <child type="quantity" id="hrmsRequired"/>
    <child type="quantity" id="hrmsFound"/>
</node>

<node type="quantity" id="hrmsFormula" value="formula">
    <regexp parsegroup="1">
        (?=
            \w{4,}
        )
        (
            <insert idref="FORMULA"/>
        )
    </regexp>
</node>

<node type="quantity" id="hrmsIon" value="ion">
    <regexp parsegroup="1">
        (
            <insert idref="hrmsIon"/>
        )
    </regexp>
</node>

<node type="quantity" id="hrmsRequired" value="required">
    <regexp parsegroup="1">
        <insert idref="hrmsRequired"/>
        <insert idref="hrmsPadding"/>* \W*
        ({1}
            <insert idref="hrmsData"/>
        )
    </regexp>
    <child type="value" id="value"/>
</node>

<node type="quantity" id="hrmsFound" value="found">
    <regexp parsegroup="1">
        <insert idref="hrmsFound"/>
        <insert idref="hrmsPadding"/>*
        \W*
        ({1}
            <insert idref="hrmsData"/>
        )
    </regexp>
    <child type="value" id="value"/>
</node>



                                                                                <!-- mass spec -->
<node type="spectrum" id="massSpec" value="massSpec">
    <regexp parsegroup="0">
	(?:
        (?:
            (?:
                (?x-i)
                <!-- MS method e.g. LCMS -->
                (?!HR)
                \b [A-Z<insert idref="HYPHENCHARACTERS"/>]* MS \b
                (?:
                    (?! \( )
                    \W
                )*?
            |
            	<!-- m/z or m/e -->
                m \/ [ez]
                (?:
                    (?! \( )
                    \W
                )*?
            <!-- one or more of either -->
            )+
        )
        (?:
            <insert idref="ALLBRACKET"/>
            [\s:]*
        )?
        <insert idref="massSpecPeakBlock"/>
    ) | (?:
    	(?:\/?\b\d+(?:\.\d+)?\b)+
    	\s*<insert idref="massSpecFragment"/>
    	(?!\w) <!-- excludes e.g. "100 MHz" -->
    ) | (?:
        <insert idref="massSpecFragment"/>\s*[:;=\s]\s*
        (?:\/?\b\d+(?:\.\d+)?\b)+
    )
    </regexp>
    <child type="quantity" id="massSpecMethod"/>
    <child type="peaks" id="massSpec"/>
</node>

<node type="quantity" id="massSpecMethod" value="method">
    <regexp parsegroup="1">
        [\(\[]
        \b (
            (?:
                <insert idref="massSpecListMethod"/>
                \b (\+)?
                (
                    \W+
                    \d+
                    \s*
                    ev
                )?
                [\s,]*?
            )+
        )
        [\)\]]?
    </regexp>
</node>

<node type="peaks" id="massSpec" value="..">
    <regexp parsegroup="1">
        (
            <insert idref="massSpecPeakBlock"/>
        ) $
    </regexp>
    <child type="peak" id="massSpec"/>
</node>

<node type="peak" id="massSpec">
    <regexp parsegroup="1">
<!--         (?=
            \d
        ) \b	 -->
        (
            <insert idref="massSpecPeak"/>
        )
    </regexp>
    <child type="quantity" id="massSpecMass"/>
    <child type="quantity" id="massSpecAssignment"/>    
    <child type="quantity" id="massSpecIntensity"/>
    <child type="quantity" id="massSpecComment"/>
</node>

<node type="quantity" id="massSpecMass" value="mass">
    <regexp parsegroup="1">
        (
            \d{2,}
            (?:
                \.
                \d+
            )?
        )
    </regexp>
    <unique/>
    <child type="value" id="value"/>
</node>

<node type="quantity" id="massSpecAssignment" value="assignment">
	<regexp parsegroup="0">
		<insert idref="massSpecFragment"/>
	</regexp>
    <unique/>
</node>

<node type="quantity" id="massSpecIntensity" value="intensity">
    <regexp parsegroup="1">
        \b (
            \d+
            (?:
                \.
                \d+
            )?
            \%?
        )
        (?(?&lt;=\%)|\b)
        \s*
        (?:
            (?&lt;= \% )
            |
            [\,\)]
        )
        ,?
    </regexp>
    <unique/>
    <child type="value" id="value"/>
    <child type="units" id="percent"/>
</node>

<node type="quantity" id="massSpecComment" value="comment">
    <regexp parsegroup="1">
        [\(\{\[]
        [\s,\(\[]*
        (
            .*?
        )
        [\s,]*
        [\)\}\]]
    </regexp>
</node>


                                                                                <!-- nature -->
<node type="property" id="nature" value="nature">
    <regexp parsegroup="0">
        <insert idref="natureBlock"/>
<!--
        (?!
            .*
            <insert idref="natureBlock"/>
        )
-->
    </regexp>
    <child type="quantity" id="natureColour"/>
    <child type="quantity" id="natureStateModifier"/>
    <child type="quantity" id="natureSolidState"/>
    <child type="quantity" id="natureNonSolidState"/>
</node>

<node type="quantity" id="natureColour" value="colour">
    <regexp parsegroup="1">
        <insert idref="natureColour"/>
    </regexp>
</node>

<node type="quantity" id="natureStateModifier" value="statemodifier">
    <regexp parsegroup="1">
        \&lt; (
            <insert idref="natureListStateModifier"/>
        ) \&gt;
    </regexp>
</node>

<node type="quantity" id="natureSolidState" value="solidstate">
    <regexp parsegroup="1">
        \&lt; (
            <insert idref="natureListSolidState"/>
        ) \&gt;
    </regexp>
</node>

<node type="quantity" id="natureNonSolidState" value="nonsolidstate">
    <regexp parsegroup="1">
        \&lt; (
            <insert idref="natureListNonSolidState"/>
        ) \&gt;
    </regexp>
</node>

                                                                                <!-- yield -->
<node type="property" id="yield" value="yield" saf="yes">
    <regexp parsegroup="0">
        <insert idref="yieldBlock"/>
    </regexp>
    <child type="quantity" id="yieldPercent"/>
    <child type="quantity" id="yieldMass"/>
    <child type="quantity" id="yieldAmount"/>
</node>

<node type="quantity" id="yieldPercent" value="percent">
    <regexp parsegroup="1">
        <insert idref="yieldPercent"/>
    </regexp>
    <child type="value" id="value"/>
    <child type="units" id="percent"/>
</node>

<node type="quantity" id="yieldMass" value="mass">
    <regexp parsegroup="1">
        <insert idref="yieldMass"/>
    </regexp>
    <child type="value" id="value"/>
    <child type="units" id="mass"/>
</node>

<node type="quantity" id="yieldAmount" value="amount">
    <regexp parsegroup="1">
        <insert idref="yieldQuantity"/>
    </regexp>
    <child type="value" id="value"/>
    <child type="units" id="amount"/>
</node>


                                                                                <!-- quantity -->
<node type="property" id="quantity" value="quantity" saf="yes">
    <regexp parsegroup="0">
        <insert idref="quantityBlock"/>
    </regexp>
    <child type="quantity" id="quantityAmount"/>
    <child type="quantity" id="quantityMass"/>
    <child type="quantity" id="quantityVolume"/>
    <child type="quantity" id="quantityEquiv"/>
    <child type="quantity" id="quantityConc"/>
    <child type="quantity" id="quantityTime"/>
    <child type="quantity" id="quantityTemp"/>
</node>

<node type="quantity" id="quantityAmount" value="amount">
    <regexp parsegroup="1">
        <insert idref="quantityAmount"/>
    </regexp>
    <child type="value" id="value"/>
    <child type="units" id="amount"/>
</node>

<node type="quantity" id="quantityMass" value="mass">
    <regexp parsegroup="1">
        <insert idref="quantityMass"/>
    </regexp>
    <child type="value" id="value"/>
    <child type="units" id="mass"/>
</node>

<node type="quantity" id="quantityVolume" value="volume">
    <regexp parsegroup="1">
        <insert idref="quantityVolume"/>
    </regexp>
    <child type="value" id="value"/>
    <child type="units" id="volume"/>
</node>

<node type="quantity" id="quantityEquiv" value="equiv">
    <regexp parsegroup="1">
        <insert idref="quantityEquiv"/>
    </regexp>
    <child type="value" id="value"/>
    <child type="units" id="equiv"/>
</node>

<node type="quantity" id="quantityConc" value="conc">
    <regexp parsegroup="1">
        <insert idref="quantityConc"/>
    </regexp>
    <child type="value" id="value"/>
    <child type="units" id="conc"/>
</node>

<node type="quantity" id="quantityTime" value="time">
    <regexp parsegroup="1">
        <insert idref="quantityTime"/>
    </regexp>
    <child type="value" id="value"/>
    <child type="units" id="time"/>
</node>

<node type="quantity" id="quantityTemp" value="temperature">
    <regexp parsegroup="1">
        <insert idref="quantityTemp"/>
    </regexp>
    <child type="value" id="value"/>
    <child type="units" id="temp"/>
</node>




                                                                                <!-- MP -->
<node type="property" id="mp" value="mp">
    <regexp parsegroup="0">
        \b (
            m\.?p\.?
            |
            melted
            (?: \s* at )?
        ) (
            \s*
            <insert idref="BRACKET"/>
        )?
        \W+
        (
            <insert idref="RANGE"/>|<insert idref="FLOAT"/>
        )
        \s*
        .C
        (?:
            (\W*lit.*?\d\W*.C\s*\d*\s*[\]\)]?)
            |
            (\W*dec\w*\.?[\]\)]?)
            |
            \W* \( from [^\(\)]+ \)
        )*
    </regexp>
    <child type="quantity" id="mpSolvent"/>
    <child type="quantity" id="mpDeleteProlog"/>
    <child type="quantity" id="mpTemp"/>
    <child type="quantity" id="mpLitValue"/>
    <child type="quantity" id="mpComment"/>
    <child type="quantity" id="mpSolvent2"/>
</node>

<node type="quantity" id="mpSolvent" value="solvent">
    <regexp parsegroup="1">
        ^m\.?p\.?\s*\((.*?)\)\s*(?=\d)
    </regexp>
</node>

<node type="quantity" id="mpDeleteProlog" value=".."> <!-- TODO -->
    <regexp parsegroup="1">
        ^
        (
            [^\d<insert idref="HYPHENCHARACTERS"/>&gt;]+
        )
    </regexp>
</node>

<node type="quantity" id="mpTemp" value="temp">
    <regexp parsegroup="1">
        (
            (?:
                <insert idref="RANGE"/>
                |
                <insert idref="FLOAT"/>
            )
            \s*
            .C
        )
    </regexp>
    <unique/>
    <child type="value" id="value"/>
    <child type="units" id="temp"/>
</node>

<node type="quantity" id="mpLitValue" value="litvalue">
    <regexp parsegroup="1">
        lit.*?
        (
            (?:
                <insert idref="RANGE"/>
                |
                <insert idref="FLOAT"/>
            )
            \s*
            .C
        )
    </regexp>
    <child type="value" id="value"/>
    <child type="units" id="temp"/>
</node>

<node type="quantity" id="mpComment" value="comment">
    <regexp parsegroup="1">
        (
            \b
            dec
            \w*
            \.?
        )
    </regexp>
</node>

<node type="quantity" id="mpSolvent2" value="solvent">
    <regexp parsegroup="1">
        \(